// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZX1WysOwTBqBpmTLO3n0fh4I2R-7pUtg',
    appId: '1:83658025458:web:2ae25efe52fe00c5f4a36b',
    messagingSenderId: '83658025458',
    projectId: 'fir-try-55b42',
    authDomain: 'fir-try-55b42.firebaseapp.com',
    storageBucket: 'fir-try-55b42.appspot.com',
    measurementId: 'G-C8T2SMECWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa-0Iz4YaEz-gHp25_zhqpeoUqVAotYbs',
    appId: '1:83658025458:android:3ee13d677723c26bf4a36b',
    messagingSenderId: '83658025458',
    projectId: 'fir-try-55b42',
    storageBucket: 'fir-try-55b42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6rabXHroXXhmqP3sGBzE2sy10ZysSg0',
    appId: '1:83658025458:ios:81fd174d94bf3750f4a36b',
    messagingSenderId: '83658025458',
    projectId: 'fir-try-55b42',
    storageBucket: 'fir-try-55b42.appspot.com',
    iosClientId: '83658025458-eql3j12fu9gu6orcd62350aon1p2kqhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO6rabXHroXXhmqP3sGBzE2sy10ZysSg0',
    appId: '1:83658025458:ios:81fd174d94bf3750f4a36b',
    messagingSenderId: '83658025458',
    projectId: 'fir-try-55b42',
    storageBucket: 'fir-try-55b42.appspot.com',
    iosClientId: '83658025458-eql3j12fu9gu6orcd62350aon1p2kqhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTry',
  );
}
